/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ActivitiesRouteImport } from './routes/activities'
import { Route as ArtistsRouteImport } from './routes/artists'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as LocationsRouteImport } from './routes/locations'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ProgramRouteImport } from './routes/program'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as TicketsRouteImport } from './routes/tickets'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminGateRouteImport } from './routes/admin/_gate'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminGateActivitiesRouteImport } from './routes/admin/_gate/activities'
import { Route as AdminGateArtistsRouteImport } from './routes/admin/_gate/artists'
import { Route as AdminGateDashboardRouteImport } from './routes/admin/_gate/dashboard'
import { Route as AdminGateGalleryRouteImport } from './routes/admin/_gate/gallery'
import { Route as AdminGateLocationsRouteImport } from './routes/admin/_gate/locations'
import { Route as AdminGateMessagesRouteImport } from './routes/admin/_gate/messages'
import { Route as AdminGateProgramRouteImport } from './routes/admin/_gate/program'
import { Route as AdminGateSettingsRouteImport } from './routes/admin/_gate/settings'
import { Route as AdminGateSubscribersRouteImport } from './routes/admin/_gate/subscribers'
import { Route as AdminGateTicketsRouteImport } from './routes/admin/_gate/tickets'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivitiesRoute = ActivitiesRouteImport.update({
  id: '/activities',
  path: '/activities',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtistsRoute = ArtistsRouteImport.update({
  id: '/artists',
  path: '/artists',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsRoute = LocationsRouteImport.update({
  id: '/locations',
  path: '/locations',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramRoute = ProgramRouteImport.update({
  id: '/program',
  path: '/program',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const TicketsRoute = TicketsRouteImport.update({
  id: '/tickets',
  path: '/tickets',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminGateRoute = AdminGateRouteImport.update({
  id: '/admin/_gate',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminGateActivitiesRoute = AdminGateActivitiesRouteImport.update({
  id: '/activities',
  path: '/activities',
  getParentRoute: () => AdminGateRoute,
} as any)
const AdminGateArtistsRoute = AdminGateArtistsRouteImport.update({
  id: '/artists',
  path: '/artists',
  getParentRoute: () => AdminGateRoute,
} as any)
const AdminGateDashboardRoute = AdminGateDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminGateRoute,
} as any)
const AdminGateGalleryRoute = AdminGateGalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => AdminGateRoute,
} as any)
const AdminGateLocationsRoute = AdminGateLocationsRouteImport.update({
  id: '/locations',
  path: '/locations',
  getParentRoute: () => AdminGateRoute,
} as any)
const AdminGateMessagesRoute = AdminGateMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AdminGateRoute,
} as any)
const AdminGateProgramRoute = AdminGateProgramRouteImport.update({
  id: '/program',
  path: '/program',
  getParentRoute: () => AdminGateRoute,
} as any)
const AdminGateSettingsRoute = AdminGateSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminGateRoute,
} as any)
const AdminGateSubscribersRoute = AdminGateSubscribersRouteImport.update({
  id: '/subscribers',
  path: '/subscribers',
  getParentRoute: () => AdminGateRoute,
} as any)
const AdminGateTicketsRoute = AdminGateTicketsRouteImport.update({
  id: '/tickets',
  path: '/tickets',
  getParentRoute: () => AdminGateRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/activities': typeof ActivitiesRoute
  '/artists': typeof ArtistsRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/faq': typeof FaqRoute
  '/gallery': typeof GalleryRoute
  '/locations': typeof LocationsRoute
  '/privacy': typeof PrivacyRoute
  '/program': typeof ProgramRoute
  '/terms': typeof TermsRoute
  '/tickets': typeof TicketsRoute
  '/admin': typeof AdminGateRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/activities': typeof AdminGateActivitiesRoute
  '/admin/artists': typeof AdminGateArtistsRoute
  '/admin/dashboard': typeof AdminGateDashboardRoute
  '/admin/gallery': typeof AdminGateGalleryRoute
  '/admin/locations': typeof AdminGateLocationsRoute
  '/admin/messages': typeof AdminGateMessagesRoute
  '/admin/program': typeof AdminGateProgramRoute
  '/admin/settings': typeof AdminGateSettingsRoute
  '/admin/subscribers': typeof AdminGateSubscribersRoute
  '/admin/tickets': typeof AdminGateTicketsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/activities': typeof ActivitiesRoute
  '/artists': typeof ArtistsRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/faq': typeof FaqRoute
  '/gallery': typeof GalleryRoute
  '/locations': typeof LocationsRoute
  '/privacy': typeof PrivacyRoute
  '/program': typeof ProgramRoute
  '/terms': typeof TermsRoute
  '/tickets': typeof TicketsRoute
  '/admin': typeof AdminIndexRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/activities': typeof AdminGateActivitiesRoute
  '/admin/artists': typeof AdminGateArtistsRoute
  '/admin/dashboard': typeof AdminGateDashboardRoute
  '/admin/gallery': typeof AdminGateGalleryRoute
  '/admin/locations': typeof AdminGateLocationsRoute
  '/admin/messages': typeof AdminGateMessagesRoute
  '/admin/program': typeof AdminGateProgramRoute
  '/admin/settings': typeof AdminGateSettingsRoute
  '/admin/subscribers': typeof AdminGateSubscribersRoute
  '/admin/tickets': typeof AdminGateTicketsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/activities': typeof ActivitiesRoute
  '/artists': typeof ArtistsRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/faq': typeof FaqRoute
  '/gallery': typeof GalleryRoute
  '/locations': typeof LocationsRoute
  '/privacy': typeof PrivacyRoute
  '/program': typeof ProgramRoute
  '/terms': typeof TermsRoute
  '/tickets': typeof TicketsRoute
  '/admin/_gate': typeof AdminGateRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/_gate/activities': typeof AdminGateActivitiesRoute
  '/admin/_gate/artists': typeof AdminGateArtistsRoute
  '/admin/_gate/dashboard': typeof AdminGateDashboardRoute
  '/admin/_gate/gallery': typeof AdminGateGalleryRoute
  '/admin/_gate/locations': typeof AdminGateLocationsRoute
  '/admin/_gate/messages': typeof AdminGateMessagesRoute
  '/admin/_gate/program': typeof AdminGateProgramRoute
  '/admin/_gate/settings': typeof AdminGateSettingsRoute
  '/admin/_gate/subscribers': typeof AdminGateSubscribersRoute
  '/admin/_gate/tickets': typeof AdminGateTicketsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/activities'
    | '/artists'
    | '/checkout'
    | '/contact'
    | '/cookies'
    | '/faq'
    | '/gallery'
    | '/locations'
    | '/privacy'
    | '/program'
    | '/terms'
    | '/tickets'
    | '/admin'
    | '/admin/login'
    | '/admin/'
    | '/admin/activities'
    | '/admin/artists'
    | '/admin/dashboard'
    | '/admin/gallery'
    | '/admin/locations'
    | '/admin/messages'
    | '/admin/program'
    | '/admin/settings'
    | '/admin/subscribers'
    | '/admin/tickets'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/activities'
    | '/artists'
    | '/checkout'
    | '/contact'
    | '/cookies'
    | '/faq'
    | '/gallery'
    | '/locations'
    | '/privacy'
    | '/program'
    | '/terms'
    | '/tickets'
    | '/admin'
    | '/admin/login'
    | '/admin/activities'
    | '/admin/artists'
    | '/admin/dashboard'
    | '/admin/gallery'
    | '/admin/locations'
    | '/admin/messages'
    | '/admin/program'
    | '/admin/settings'
    | '/admin/subscribers'
    | '/admin/tickets'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/activities'
    | '/artists'
    | '/checkout'
    | '/contact'
    | '/cookies'
    | '/faq'
    | '/gallery'
    | '/locations'
    | '/privacy'
    | '/program'
    | '/terms'
    | '/tickets'
    | '/admin/_gate'
    | '/admin/login'
    | '/admin/'
    | '/admin/_gate/activities'
    | '/admin/_gate/artists'
    | '/admin/_gate/dashboard'
    | '/admin/_gate/gallery'
    | '/admin/_gate/locations'
    | '/admin/_gate/messages'
    | '/admin/_gate/program'
    | '/admin/_gate/settings'
    | '/admin/_gate/subscribers'
    | '/admin/_gate/tickets'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ActivitiesRoute: typeof ActivitiesRoute
  ArtistsRoute: typeof ArtistsRoute
  CheckoutRoute: typeof CheckoutRoute
  ContactRoute: typeof ContactRoute
  CookiesRoute: typeof CookiesRoute
  FaqRoute: typeof FaqRoute
  GalleryRoute: typeof GalleryRoute
  LocationsRoute: typeof LocationsRoute
  PrivacyRoute: typeof PrivacyRoute
  ProgramRoute: typeof ProgramRoute
  TermsRoute: typeof TermsRoute
  TicketsRoute: typeof TicketsRoute
  AdminGateRoute: typeof AdminGateRouteWithChildren
  AdminLoginRoute: typeof AdminLoginRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activities': {
      id: '/activities'
      path: '/activities'
      fullPath: '/activities'
      preLoaderRoute: typeof ActivitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artists': {
      id: '/artists'
      path: '/artists'
      fullPath: '/artists'
      preLoaderRoute: typeof ArtistsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations': {
      id: '/locations'
      path: '/locations'
      fullPath: '/locations'
      preLoaderRoute: typeof LocationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/program': {
      id: '/program'
      path: '/program'
      fullPath: '/program'
      preLoaderRoute: typeof ProgramRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tickets': {
      id: '/tickets'
      path: '/tickets'
      fullPath: '/tickets'
      preLoaderRoute: typeof TicketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_gate': {
      id: '/admin/_gate'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminGateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_gate/activities': {
      id: '/admin/_gate/activities'
      path: '/activities'
      fullPath: '/admin/activities'
      preLoaderRoute: typeof AdminGateActivitiesRouteImport
      parentRoute: typeof AdminGateRoute
    }
    '/admin/_gate/artists': {
      id: '/admin/_gate/artists'
      path: '/artists'
      fullPath: '/admin/artists'
      preLoaderRoute: typeof AdminGateArtistsRouteImport
      parentRoute: typeof AdminGateRoute
    }
    '/admin/_gate/dashboard': {
      id: '/admin/_gate/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminGateDashboardRouteImport
      parentRoute: typeof AdminGateRoute
    }
    '/admin/_gate/gallery': {
      id: '/admin/_gate/gallery'
      path: '/gallery'
      fullPath: '/admin/gallery'
      preLoaderRoute: typeof AdminGateGalleryRouteImport
      parentRoute: typeof AdminGateRoute
    }
    '/admin/_gate/locations': {
      id: '/admin/_gate/locations'
      path: '/locations'
      fullPath: '/admin/locations'
      preLoaderRoute: typeof AdminGateLocationsRouteImport
      parentRoute: typeof AdminGateRoute
    }
    '/admin/_gate/messages': {
      id: '/admin/_gate/messages'
      path: '/messages'
      fullPath: '/admin/messages'
      preLoaderRoute: typeof AdminGateMessagesRouteImport
      parentRoute: typeof AdminGateRoute
    }
    '/admin/_gate/program': {
      id: '/admin/_gate/program'
      path: '/program'
      fullPath: '/admin/program'
      preLoaderRoute: typeof AdminGateProgramRouteImport
      parentRoute: typeof AdminGateRoute
    }
    '/admin/_gate/settings': {
      id: '/admin/_gate/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminGateSettingsRouteImport
      parentRoute: typeof AdminGateRoute
    }
    '/admin/_gate/subscribers': {
      id: '/admin/_gate/subscribers'
      path: '/subscribers'
      fullPath: '/admin/subscribers'
      preLoaderRoute: typeof AdminGateSubscribersRouteImport
      parentRoute: typeof AdminGateRoute
    }
    '/admin/_gate/tickets': {
      id: '/admin/_gate/tickets'
      path: '/tickets'
      fullPath: '/admin/tickets'
      preLoaderRoute: typeof AdminGateTicketsRouteImport
      parentRoute: typeof AdminGateRoute
    }
  }
}

interface AdminGateRouteChildren {
  AdminGateActivitiesRoute: typeof AdminGateActivitiesRoute
  AdminGateArtistsRoute: typeof AdminGateArtistsRoute
  AdminGateDashboardRoute: typeof AdminGateDashboardRoute
  AdminGateGalleryRoute: typeof AdminGateGalleryRoute
  AdminGateLocationsRoute: typeof AdminGateLocationsRoute
  AdminGateMessagesRoute: typeof AdminGateMessagesRoute
  AdminGateProgramRoute: typeof AdminGateProgramRoute
  AdminGateSettingsRoute: typeof AdminGateSettingsRoute
  AdminGateSubscribersRoute: typeof AdminGateSubscribersRoute
  AdminGateTicketsRoute: typeof AdminGateTicketsRoute
}

const AdminGateRouteChildren: AdminGateRouteChildren = {
  AdminGateActivitiesRoute: AdminGateActivitiesRoute,
  AdminGateArtistsRoute: AdminGateArtistsRoute,
  AdminGateDashboardRoute: AdminGateDashboardRoute,
  AdminGateGalleryRoute: AdminGateGalleryRoute,
  AdminGateLocationsRoute: AdminGateLocationsRoute,
  AdminGateMessagesRoute: AdminGateMessagesRoute,
  AdminGateProgramRoute: AdminGateProgramRoute,
  AdminGateSettingsRoute: AdminGateSettingsRoute,
  AdminGateSubscribersRoute: AdminGateSubscribersRoute,
  AdminGateTicketsRoute: AdminGateTicketsRoute,
}

const AdminGateRouteWithChildren = AdminGateRoute._addFileChildren(
  AdminGateRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ActivitiesRoute: ActivitiesRoute,
  ArtistsRoute: ArtistsRoute,
  CheckoutRoute: CheckoutRoute,
  ContactRoute: ContactRoute,
  CookiesRoute: CookiesRoute,
  FaqRoute: FaqRoute,
  GalleryRoute: GalleryRoute,
  LocationsRoute: LocationsRoute,
  PrivacyRoute: PrivacyRoute,
  ProgramRoute: ProgramRoute,
  TermsRoute: TermsRoute,
  TicketsRoute: TicketsRoute,
  AdminGateRoute: AdminGateRouteWithChildren,
  AdminLoginRoute: AdminLoginRoute,
  AdminIndexRoute: AdminIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
